# Generated by Django 5.1.1 on 2024-09-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام')),
                ('last_name', models.CharField(max_length=20, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=20, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=11, verbose_name='تلفن')),
                ('description', models.CharField(max_length=250, verbose_name='متن')),
                ('subject', models.CharField(max_length=250, verbose_name='موضوع')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=500, verbose_name='توضیحات'),
        ),
    ]
