# Generated by Django 5.1.1 on 2024-09-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_ticket_alter_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='ایمیل'),
        ),
    ]
