# Generated by Django 5.1.1 on 2024-09-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_remove_ticket_last_name_alter_ticket_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_name',
            field=models.CharField(default='me', max_length=20, verbose_name='نام خانوادگی'),
        ),
    ]
