# Generated by Django 5.1.1 on 2024-09-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reading_time',
            field=models.IntegerField(default=0, verbose_name='زمان مطالعه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='budy',
            field=models.TextField(max_length=300, verbose_name='متن کامنت'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='fullname',
            field=models.CharField(max_length=20, verbose_name='نام و نام خانوادگی'),
        ),
    ]
