# Generated by Django 5.1.1 on 2024-09-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_post_reading_time_alter_comment_budy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reading_time',
            field=models.PositiveIntegerField(verbose_name='زمان مطالعه'),
        ),
    ]
