# Generated by Django 5.1.1 on 2024-09-22 11:54

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_image_delete_images_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created'], 'verbose_name': 'تصویر', 'verbose_name_plural': 'تصویر ها'},
        ),
        migrations.AlterField(
            model_name='image',
            name='file_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center', 'right'], force_format=None, keep_meta=True, max_length=250, null=True, quality=-1, scale=None, size=[300, 300], upload_to='post_image/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان'),
        ),
    ]
