# Generated by Django 5.1.1 on 2024-09-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_alter_image_options_alter_image_file_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['created'], 'verbose_name': 'تصویر', 'verbose_name_plural': 'تصویر ها'},
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='mysite_imag_created_4f274e_idx',
        ),
        migrations.AlterField(
            model_name='image',
            name='file_image',
            field=models.ImageField(upload_to='post_image/'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['created'], name='mysite_imag_created_c0df2c_idx'),
        ),
    ]
