# Generated by Django 5.1.1 on 2024-09-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_image/'),
        ),
    ]
