# Generated by Django 5.1.1 on 2024-09-22 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_alter_image_file_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['publish'], 'verbose_name_plural': 'پست ها'},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='mysite_post_publish_3214db_idx',
        ),
        migrations.AlterField(
            model_name='image',
            name='file_image',
            field=models.ImageField(upload_to='post_image/'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['publish'], name='mysite_post_publish_bdbc0e_idx'),
        ),
    ]
