# Generated by Django 5.1.1 on 2024-09-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_alter_image_file_image_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('هوش مصنوعی', 'هوش مصنوعی'), ('برنامه نویسی', 'برنامه نویسی'), ('تکنولوژی', 'تکنولوژی'), ('سایر', 'سایر')], default='سایر', verbose_name='دسته بندی'),
        ),
    ]
